gofresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from full_scope_api import api

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^', include('stores.urls', namespace='stores')),
    url(r'^', include('orders.urls', namespace='orders')),
    url(r'^', include('products.urls', namespace='products')),
    url(r'^full_scope_api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^get_initial_information/$', api.get_initial_information, name='get_initial_information'),
]

orders/urls.py
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter
from orders import views as order_view

router = DefaultRouter()
router.register(r'delivery_info', order_view.DeliveryInformationViewSet, 'delivery_info')
router.register(r'orders', order_view.OrderViewSet, 'orders')
router.register(r'products_in_order', order_view.ProductInOrderViewSet, 'products_in_order')

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^reset_delivery_cost_form/$', order_view.reset_delivery_cost_form, name='reset_delivery_cost_form'),
    url(r'^reset_delivery_cost/$', order_view.reset_delivery_cost, name='reset_delivery_cost'),
    url(r'^create_order/$', order_view.create_order, name='create_order'),
    ]

orders/models.py
from datetime import date

from django.utils.safestring import mark_safe

from accounts.models import UserProfile
from customutils.full_scope_static import MAX_CHAR_LENGTH, DELIVERY_TIME_SLOTS, TIME_SLOT_1, \
    DELIVERY_STATUS, PENDING, MAX_INVOICE_NUMBER_LENGTH, SMALL_CHAR_LENGTH
from customutils.method_box import generate_invoice_number, get_delivery_cost
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from products.models import Product, ProductImage
from smart_selects.db_fields import ChainedForeignKey
from stores.models import Store


class DeliveryInformation(models.Model):

    phone_regex = RegexValidator(regex=r'^\+?\(?\d{2,4}\)?[\d\s-]{3,15}$',
                                 message="Phone number must be entered in the format: '+999999999' '+880155456509'. Up to 15 digits allowed.")
    user_profile = models.ForeignKey(UserProfile)
    area = models.CharField(max_length=MAX_CHAR_LENGTH, blank=False)
    road_no = models.CharField(max_length=MAX_CHAR_LENGTH, blank=True)
    house_no = models.CharField(max_length=MAX_CHAR_LENGTH, blank=True)
    floor_no = models.CharField(max_length=MAX_CHAR_LENGTH, blank=True)
    address_detail = models.CharField(max_length=MAX_CHAR_LENGTH, blank=True)

    product_receiver_name = models.CharField(max_length=MAX_CHAR_LENGTH, blank=False)
    product_receiver_phone = models.CharField(validators=[phone_regex], blank=False, max_length=15) # validators should be a list
    product_receiver_phone_optional = models.CharField(validators=[phone_regex], blank=True, max_length=15)

    date_added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)


class Order(models.Model):

    user_profile = models.ForeignKey(UserProfile, related_name='order_user_profile')
    store = models.ForeignKey(Store, related_name='orders', default=None)
    delivery_information = models.ForeignKey(DeliveryInformation, related_name='order_delivery_information')

    delivery_status = models.IntegerField(choices=DELIVERY_STATUS, default=PENDING)
    invoice_number = models.CharField(max_length=MAX_INVOICE_NUMBER_LENGTH, blank=True)

    delivery_date = models.DateField(default=date.today, blank=False)
    delivery_time = models.IntegerField(choices=DELIVERY_TIME_SLOTS, default=TIME_SLOT_1, blank=False)

    date_added = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def total_expense(self):
        
        product_list = ProductInOrder.objects.filter(order=self.id)
        total_price = 0
        for each in product_list:
            total_price += (each.product.real_price*each.quantity)
        return str(total_price+get_delivery_cost())

    total_expense.allow_tags = True

    def __str__(self):
        return str(self.invoice_number)


class ProductInOrder(models.Model):

    order = models.ForeignKey(Order, related_name='products')
    product = models.ForeignKey(Product)
    quantity = models.IntegerField(blank=False, default=1)

    class Meta:
        unique_together = ['order', 'product']

    def __str__(self):
        return str(self.order.id)


@receiver(post_save, sender=Order)
def post_save_auth_user(signal, sender, instance, **kwargs):
    if kwargs.get('created') is True:
        instance.invoice_number = generate_invoice_number()
        instance.save()

orders/views.py
from django.core.cache import cache

from accounts.models import UserProfile
from customutils.custom_authentication import AppTokenAuthentication
from django.shortcuts import render, get_object_or_404
from orders.models import DeliveryInformation, Order, ProductInOrder
from orders.serializers import DeliveryInformationSerializer, ProductInOrderSerializer, CustomProductInOrderSerializer, \
    OrderSerializer
from products.models import Product
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import status
from rest_framework import viewsets
from rest_framework.decorators import api_view, renderer_classes, authentication_classes
from rest_framework.parsers import JSONParser
from rest_framework.permissions import AllowAny
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from django.utils.six import BytesIO

from stores.models import Store


class DeliveryInformationViewSet(viewsets.ModelViewSet):

    queryset = DeliveryInformation.objects.all()
    serializer_class = DeliveryInformationSerializer
    #authentication_classes = (AppTokenAuthentication,)
    filter_backends = (DjangoFilterBackend,)
    filter_fields = ('user_profile',)


class OrderViewSet(viewsets.ModelViewSet):

    def get_serializer_class(self):

        if self.action == 'list':
            return OrderSerializer

        elif self.action == 'retrieve':
            return OrderSerializer

        elif self.action == 'create':
            print("get_serializer_class : " + "create")
            return OrderSerializer

        return OrderSerializer

    queryset = Order.objects.all()
    filter_fields = ('user_profile',)
    #permission_classes = (AllowAny,)
    serializer_class = get_serializer_class
    #authentication_classes = (AppTokenAuthentication,)
    filter_backends = (DjangoFilterBackend,)


class ProductInOrderViewSet(viewsets.ModelViewSet):

    queryset = ProductInOrder.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = ProductInOrderSerializer
    #authentication_classes = (AppTokenAuthentication,)
    filter_backends = (DjangoFilterBackend,)
    filter_fields = ('order', 'order__invoice_number')


@api_view(['POST'])
@renderer_classes((JSONRenderer,))
#@authentication_classes((AppTokenAuthentication,))
def create_order(request):

    user_profile = UserProfile.objects.get(id=request.POST.get('user_profile'))
    delivery_information = request.POST.get('delivery_information')
    delivery_date = request.POST.get('delivery_date')
    delivery_time = request.POST.get('delivery_time')
    products = request.POST.get('products')
    store_id = request.data['store_id']

    delivery_information_instance = DeliveryInformation.objects.get(id=delivery_information)
    store = Store.objects.get(id = store_id)
    order = Order.objects.create(user_profile=user_profile, delivery_information=delivery_information_instance, store= store,
                                 delivery_date=delivery_date, delivery_time=delivery_time)

    stream = BytesIO(products.encode())
    products_data = JSONParser().parse(stream)

    products_serializer = CustomProductInOrderSerializer(data=products_data, many=True)

    if products_serializer.is_valid():
        for each in products_serializer.data:
            each_product_in_order = (dict(each))
            each_product_id_in_order = Product.objects.get(id=each_product_in_order['product'])
            ProductInOrder.objects.create(order=order, product=each_product_id_in_order,
                                          quantity=each_product_in_order['quantity'])

        data = dict()
        data['invoice_number'] = order.invoice_number
        return Response(data=data, status=status.HTTP_200_OK)

    else:
        return Response(data=products_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
@renderer_classes((TemplateHTMLRenderer,))
def reset_delivery_cost_form(request):
    return Response(status=status.HTTP_200_OK, template_name='orders/delivery_cost_reset_form.html')


@api_view(['POST'])
@renderer_classes((JSONRenderer,))
def reset_delivery_cost(request):
    delivery_cost = request.POST.get('delivery_cost')
    cache.set('delivery_cost', delivery_cost, None)

    '''
    fo = open('delivery_cost.txt', 'w')
    fo.write(str(delivery_cost))
    fo.close()

    '''


    data = {'message': 'Changed'}
    return Response(data=data, status=status.HTTP_200_OK)

orders/templates/orders/delivery_cost_reset_form.html
<!DOCTYPE html>
<html>

<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>

<body>
<form action="{% url 'orders:reset_delivery_cost' %}" method="post">
    {% csrf_token %}
    Delivery cost <input type="number" name="delivery_cost" value=""><br><br>
    <input type="submit" value="Submit">
</form>
</body>
</html>

orders/templates/orders/invoice_generator.html
{% load mathfilters %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'/>

    <title>Editable Invoice</title>


</head>

<body>

<div id="page-wrap" style="max-width: 100%">
    <table border="0" width="100%">
        <tr>
            <td width="50%">
                <b style="font-size: 20px;">Go Fresh</b><br/>
                <span style="color: #666666">Go Fresh, Live Fresh</span><br/>
                18th Floor, 40 Kamal Ataturk,<br/>
                Banani, Dhaka 1213<br/>

            </td>
            <td align="right" width="50%">
                <img width="50" style="padding-bottom: 10px; padding-top: 50px;"
                     src="https://gofreshergo.s3.amazonaws.com/logo.jpg"/><br/>
                INVOICE #{{ order.invoice_number }}<br/>
                DATE: {{ order.delivery_date }}
            </td>
        </tr>
    </table>

    <br/><br/>
    <table border="0" width="100%">
        <tr>
            <td width="50%">
                TO:<br/>
                {{ order.user_profile.name }}<br/>
                {{ order.delivery_information.area }},{{ order.delivery_information.road_no }}<br/>
                {{ order.delivery_information.address_detail }} <br/>
                Phone: {{ order.delivery_information.product_receiver_phone }}
            </td>
            <td align="right" width="50%">

            </td>
        </tr>
    </table>

    </br>
    </br>
    <table border="0" width="100%" class="item_amount" cellspacing="0" cellpadding="5">
        <tr>
            <th>ITEM</th>
            <th>QUANTITY</th>
            <th>UNIT PRICE</th>
            <th>AMOUNT</th>

        </tr>

        {% for each in products_in_order %}
            <tr>
                <td><span>{{ each.product.name }}</span></td>
                <td align="center"><span class="qty">{{ each.quantity }}</span></td>
                <td align="center"><span class="cost">Tk. {{ each.product.real_price }}</span></td>
                <td align="center"><span class="price">Tk. {{ each.product.real_price|mul:each.quantity }}</span></td>
            </tr>
        {% endfor %}

        <tr>
            <td><span> Delivery cost</span></td>
            <td align="center"></td>
            <td align="center">Tk. {{ delivery_cost }}</td>
            <td align="center">Tk. {{ delivery_cost }}</td>
        </tr>

        <tr>
            <td><span> Vat </span></td>
            <td align="center"></td>
            <td align="center">Tk. {{ vat }}</td>
            <td align="center">Tk. {{ vat }}</td>
        </tr>


        <tr>
            <td class="last_item" align="right" colspan="3">Total:</td>
            <td class="last_item">Tk. {{ total_price }}</td>
        </tr>
    </table>


</div>

</body>

<style>
    .item_amount td {
        border-left: 1px solid #000000;
        border-collapse: collapse;

    }

    .item_amount {
        border: 1px solid #000000;
        border-left: 0;
        border-bottom: 0;
    }

    th {
        border: 1px solid #000000;
    }

    .last_item {
        border-bottom: 1px solid #000000;
        border-top: 1px solid #000000;

    }

    body {
        font-family: Arial, "Times New Roman", Georgia, Serif;
    }

</style>

</html>