accounts/urls.py
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter
from accounts import views as accounts_view
from accounts.views import AccountViewSet, UserProfileViewSet

router = DefaultRouter()
# router.register(r'accounts', AccountViewSet)
router.register(r'user_profile', UserProfileViewSet)

urlpatterns = [

    url(r'^', include(router.urls)),
    url(r'^registration_email/$', accounts_view.registration_email, name='registration_email'),
    url(r'^registration_fb/$', accounts_view.registration_fb, name='registration_fb'),
    url(r'^obtain_auth_token/$', accounts_view.obtain_auth_token, name='obtain_auth_token'),
    url(r'^user_by_email/$', accounts_view.user_by_email, name='user_by_email'),

    url(r'^confirm_email/(?P<email_confirmation_key>[0-9a-zA-Z]+)/$', accounts_view.confirm_email,
        name='confirm_email'),
    url(r'^resend_confirmation_email/$', accounts_view.resend_confirmation_email, name='resend_confirmation_email'),

    url(r'^forgot_password_email/', accounts_view.forgot_password_email, name='forgot_password_email'),
    url(r'^forgot_password_form/(?P<password_reset_key>[0-9a-zA-Z]+)/$', accounts_view.forgot_password_form,
        name='forgot_password_form'),
    url(r'^forgot_password/(?P<password_reset_key>[0-9a-zA-Z]+)$', accounts_view.forgot_password,
        name='forgot_password'),
    url(r'^reset_password/$', accounts_view.reset_password, name='reset_password'),

    #url(r'^update_profile/$', accounts_view.update_profile, name='update_profile'),

    url(r'^terms_and_conditions/', accounts_view.terms_and_conditions, name='terms_and_conditions'),
    url(r'^privacy_policy/', accounts_view.privacy_policy, name='privacy_policy'),
    url(r'^buy_and_return_policy/', accounts_view.buy_and_return_policy, name='buy_and_return_policy'),

]

gofresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from full_scope_api import api

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^', include('stores.urls', namespace='stores')),
    url(r'^', include('orders.urls', namespace='orders')),
    url(r'^', include('products.urls', namespace='products')),
    url(r'^full_scope_api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^get_initial_information/$', api.get_initial_information, name='get_initial_information'),
]

orders/urls.py
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter
from orders import views as order_view

router = DefaultRouter()
router.register(r'delivery_info', order_view.DeliveryInformationViewSet, 'delivery_info')
router.register(r'orders', order_view.OrderViewSet, 'orders')
router.register(r'products_in_order', order_view.ProductInOrderViewSet, 'products_in_order')

urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^reset_delivery_cost_form/$', order_view.reset_delivery_cost_form, name='reset_delivery_cost_form'),
    url(r'^reset_delivery_cost/$', order_view.reset_delivery_cost, name='reset_delivery_cost'),
    url(r'^create_order/$', order_view.create_order, name='create_order'),
    ]

accounts/views.py
from rest_framework.parsers import FormParser, MultiPartParser

from customutils.custom_authentication import AppTokenAuthentication
from customutils.custom_validators import is_email_address_valid, validate_password
from customutils.emailtasks import SendAccountVerificationEmail, ForgotPasswordEmail
from customutils.method_box import get_confirmation_email_subject_message, \
    get_forget_password_email_subject_message, create_email_confirm_key, create_password_reset_key
from accounts.models import AuthUser, EmailConfirmationKey, UserProfile, PasswordResetKey
from accounts.serializers import UserSerializer, UserProfileSerializer, UserPostSerializer
from django.contrib.auth.models import AnonymousUser
from customutils.full_scope_static import GENERAL_USER
from rest_framework import status
from rest_framework import viewsets
from rest_framework.authentication import TokenAuthentication
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, renderer_classes, authentication_classes, parser_classes
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from accounts.tasks import account_confirmation_email, forgot_password_email_send
from gofresh.settings import get_running_host


@api_view(['POST'])
@renderer_classes((JSONRenderer,))
def registration_fb(request):
    email = request.data.get('email')
    name = request.data.get('name')
    gender = request.data.get('gender')
    date_of_birth = request.data.get('date_of_birth')
    fb_access_token = request.data.get('fb_access_token')
    fb_uid = request.data.get('fb_uid')

    data = {}

    try:
        auth_user = AuthUser.objects.get(email=email)
        user_profile = UserProfile.objects.get(auth_user=auth_user)

        if user_profile.is_logged_in_from_fb is False:
            data['message'] = 'this email was previously used for email login.'
            return Response(data=data, status=status.HTTP_409_CONFLICT)
        else:
            data = get_user_info(auth_user, request)
            return Response(data=data, status=status.HTTP_200_OK)

    except AuthUser.DoesNotExist:

        user = AuthUser(email=email, user_type=GENERAL_USER)
        user.set_password('gogogofresh')
        user.is_active = True
        user.save()

        user_profile = UserProfile(auth_user=user)
        user_profile.name = name
        user_profile.gender = gender
        user_profile.date_of_birth = date_of_birth
        user_profile.is_logged_in_from_fb = True
        user_profile.fb_access_token = fb_access_token
        user_profile.fb_uid = fb_uid
        user_profile.is_active = True
        user_profile.save()

        Token.objects.create(user=user)
        data = get_user_info(user, request)

        return Response(data=data, status=status.HTTP_200_OK)


@api_view(['POST'])
@renderer_classes((JSONRenderer,))
@parser_classes((FormParser, MultiPartParser,))
def registration_email(request):
    print('aise')

    email = request.data.get('email')
    name = request.data.get('name')
    image = request.data.get('image')
    phone = request.data.get('phone')
    # phone_optional = request.POST.get('phone_optional')
    #gender = request.POST.get('gender')
    #date_of_birth = request.POST.get('date_of_birth')
    password = request.POST.get('password')

    data = {}
    if not is_email_address_valid(email):
        data['email'] = 'This is not a valid email address.'

    msg = validate_password(password)
    if msg is not None:
        data['password'] = msg

    if len(data) > 0:
        return Response(data=data, status=status.HTTP_406_NOT_ACCEPTABLE)

    try:
        auth_user = AuthUser.objects.get(email=email)
        user_profile = UserProfile.objects.get(auth_user=auth_user)

        if user_profile.is_logged_in_from_fb is True:
            data['message'] = 'this email was previously used for facebook login.'
            return Response(data=data, status=status.HTTP_409_CONFLICT)
        else:
            data['message'] = 'email address already taken.'
            return Response(data=data, status=status.HTTP_409_CONFLICT)

    except AuthUser.DoesNotExist:

        auth_user = AuthUser(email=email, user_type=GENERAL_USER)
        auth_user.set_password(password)
        auth_user.save()
        Token.objects.create(user=auth_user)

        user_profile = UserProfile(auth_user=auth_user)
        user_profile.name = name
        #print(image.name)
        if image is not None:
            user_profile.image.save(image.name, image)

        #user_profile.date_of_birth = date_of_birth
        user_profile.phone = phone
        # user_profile.phone_optional = phone_optional
        user_profile.save()

        '''
        from accounts.views import get_confirmation_email_subject_message
        subject, message = get_confirmation_email_subject_message(user)
        user.email_user(subject, message)

        '''

        email_confirmation_key = create_email_confirm_key(auth_user)
        #account_confirmation_email.delay(name, email, email_confirmation_key)
        email_thread = SendAccountVerificationEmail(name, email, email_confirmation_key)
        email_thread.start()

        data = get_user_info(auth_user, request)
        return Response(data=data, status=status.HTTP_200_OK)


@api_view(['POST'])
@renderer_classes((JSONRenderer,))
def obtain_auth_token(request):
    print('obtain_auth_token')
    email = request.POST.get('email')
    password = request.POST.get('password')
    print('email : %s password : %s' % (email, password))

    if is_email_address_valid(email):
        try:
            user = AuthUser.objects.get(email=email)
            if user.check_password(password):
                data = get_user_info(user, request)
                return Response(data=data, status=status.HTTP_200_OK)
            else:
                data = {'message': 'Password does not match with email.'}
                return Response(data=data, status=status.HTTP_406_NOT_ACCEPTABLE)

        except AuthUser.DoesNotExist:
            data = {'message': 'No user found with given email.'}
            return Response(data=data, status=status.HTTP_404_NOT_FOUND)

    else:
        data = {'message': 'This is not a valid email address.'}
        return Response(data=data, status=status.HTTP_205_RESET_CONTENT)


def get_user_info(user, request):
    data = {}
    token = Token.objects.get(user=user)
    data['token'] = token.key
    profile = UserProfile.objects.get(auth_user=user)
    profile_serializer = UserProfileSerializer(profile, context={"request": request})
    data['profile'] = profile_serializer.data

    return data

    """
    After confirming email user will be active means user got write access.
    * user active means he has read and write access
    * user not active means he has only read access
    """


@api_view(['GET'])
@renderer_classes((JSONRenderer,))
def confirm_email(request, email_confirmation_key):
    try:
        eck = EmailConfirmationKey.objects.get(key=email_confirmation_key)
        eck.auth_user.is_active = True
        eck.auth_user.save()
        user_profile = UserProfile.objects.get(auth_user=eck.auth_user)
        user_profile.is_active = True
        user_profile.save()

        eck_list = EmailConfirmationKey.objects.filter(auth_user=eck.auth_user)
        for each_eck in eck_list:
            each_eck.delete()

        data = {'message': 'email confirmed.'}
        return Response(data=data, status=status.HTTP_200_OK)

    except EmailConfirmationKey.DoesNotExist:
        data = {'message': 'invalid email confirmation key'}
        return Response(data=data, status=status.HTTP_400_BAD_REQUEST)

    """
    * User can login even he is not confirmed his email yet.
    * After login user will be shown a "Resend confirmation email" button in home screen if not confirmed yet.
    * Only logged in user can send confirmation email again.
"""


@api_view(['GET'])
@renderer_classes((JSONRenderer,))
@authentication_classes((AppTokenAuthentication,))
def resend_confirmation_email(request):
    if isinstance(request.user, AnonymousUser):
        error_message = {'error_message': 'you are not authorized to access this functionality.'}
        return Response(data=error_message, status=status.HTTP_401_UNAUTHORIZED)

    subject, message = get_confirmation_email_subject_message(request.user)
    if request.user.email_user(subject, message):
        print('email sent successfully.')
        data = {'message': 'confirmation email sent'}
        return Response(data=data, status=status.HTTP_200_OK)
    else:
        print('email did not sent.')
        data = {'message': 'confirmation email was not sent.Check you email address and resend'}
        return Response(data=data, status=status.HTTP_200_OK)


"""
    * This method will be used after getting sure that
    a user is present in the database with given email.
    * Use 'user_by_email' method to be sure that a user with given email is there.
"""


@api_view(['POST'])
@renderer_classes((JSONRenderer,))
def forgot_password_email(request):

    user = AuthUser.objects.get(email=request.POST.get('email'))
    user_profile = UserProfile.objects.get(auth_user=user)

    password_reset_key = create_password_reset_key(user)
    password_reset_link = get_running_host() + "/forgot_password_form/" + password_reset_key + "/"

    fpe = ForgotPasswordEmail(user_profile.name, user.email, password_reset_link)
    fpe.start()

    data = {'message': 'forget password email sent'}
    return Response(data=data, status=status.HTTP_200_OK)


"""
will be clicked from email
"""

@api_view(['GET'])
@renderer_classes((TemplateHTMLRenderer,))
def forgot_password_form(request, password_reset_key):
    try:
        prk = PasswordResetKey.objects.get(key=password_reset_key)
        data = {'password_reset_key': prk.key}

accounts/templates/accounts/buy_and_return_policy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Buy and Return Policy</title>
    <style>
        .title{
            text-align:center;
        }
    </style>
</head>
<body>
<h1 class="title">Buy and Return Policy</h1>
<p>Last updated: (12-8-2016)</p>
<p>
Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using
the http://www.mywebsite.com (change this) website and the My Mobile App (change this) mobile
application (the "Service") operated by My Company (change this) ("us", "we", or "our").
Your access to and use of the Service is conditioned on your acceptance of and compliance with
these Terms. These Terms apply to all visitors, users and others who access or use the Service.
By accessing or using the Service you agree to be bound by these Terms. If you disagree
with any part of the terms then you may not access the Service. </p>
<h2>Purchases</h2>
<p>
If you wish to purchase any product or service made available through the Service ("Purchase"),
you may be asked to supply certain information relevant to your Purchase including, without
limitation, your …
The Purchases section is for businesses that sell online (physical or digital). For the full
disclosure section, create your own Terms and Conditions.
    </p>
<h2>Subscriptions</h2>
    <p>
Some parts of the Service are billed on a subscription basis ("Subscription(s)"). You will be billed in
advance on a recurring ...
The Subscriptions section is for SaaS businesses. For the full disclosure section, create your
own Terms and Conditions.
        </p>
<h2>Content</h2>
    <p>
Our Service allows you to post, link, store, share and otherwise make available certain information,
text, graphics, videos, or other material ("Content"). You are responsible for the …
The Content section is for businesses that allow users to create, edit, share, make content on
their websites or apps. For the full disclosure section, create your own Terms and Conditions.
Links To Other Web Sites
Our Service may contain links to third­party web sites or services that are not owned or controlled
by My Company (change this).
My Company (change this) has no control over, and assumes no responsibility for, the content,
privacy policies, or practices of any third party web sites or services. You further acknowledge and
agree that My Company (change this) shall not be responsible or liable, directly or indirectly, for any
damage or loss caused or alleged to be caused by or in connection with use of or reliance on any
such content, goods or services available on or through any such web sites or services.
        </p>
<h2>Changes</h2>
    <p>
We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a
revision is material we will try to provide at least 30 (change this) days' notice prior to any new terms
taking effect. What constitutes a material change will be determined at our sole discretion.
Contact Us
If you have any questions about these Terms, please contact us.
    </p>

</body>
</html>

accounts/templates/accounts/forgot_password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<h5>Hello {{ name }}</h5><br>
<h4><a href="{{ password_reset_link }}">Click here</a> to reset your password.</h4>

</body>
</html>

accounts/templates/accounts/invalid_password_reset_key.html
<!DOCTYPE html>
<html>

<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>

<body>

{{ error_message }}

</body>
</html>

accounts/templates/accounts/password_reset_form.html
<!DOCTYPE html>
<html>

<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>

<body>
<form action="{% url 'accounts:forgot_password' password_reset_key %}" method="post">
{% csrf_token %}
    Password       <input type="password" name="password" value=""><br><br>
    Repeat-Password<input type="password" name="repeat_password" value=""><br><br>
    <input type="reset" value="Reset">
    <input type="submit" value="Submit">
</form>
</body>
</html>

accounts/templates/accounts/privacy_policy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Terms and Conditions</title>
    <style>
        .title{
            text-align:center;
        }
    </style>
</head>
<body>
<h1 class="title">Privacy Policy</h1>
<p>Last updated: (12-8-2016)</p>
<p>
Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using
the http://www.mywebsite.com (change this) website and the My Mobile App (change this) mobile
application (the "Service") operated by My Company (change this) ("us", "we", or "our").
Your access to and use of the Service is conditioned on your acceptance of and compliance with
these Terms. These Terms apply to all visitors, users and others who access or use the Service.
By accessing or using the Service you agree to be bound by these Terms. If you disagree
with any part of the terms then you may not access the Service. </p>
<h2>Purchases</h2>
<p>
If you wish to purchase any product or service made available through the Service ("Purchase"),
you may be asked to supply certain information relevant to your Purchase including, without
limitation, your …
The Purchases section is for businesses that sell online (physical or digital). For the full
disclosure section, create your own Terms and Conditions.
    </p>
<h2>Subscriptions</h2>
    <p>
Some parts of the Service are billed on a subscription basis ("Subscription(s)"). You will be billed in
advance on a recurring ...
The Subscriptions section is for SaaS businesses. For the full disclosure section, create your
own Terms and Conditions.
        </p>
<h2>Content</h2>
    <p>
Our Service allows you to post, link, store, share and otherwise make available certain information,
text, graphics, videos, or other material ("Content"). You are responsible for the …
The Content section is for businesses that allow users to create, edit, share, make content on
their websites or apps. For the full disclosure section, create your own Terms and Conditions.
Links To Other Web Sites
Our Service may contain links to third­party web sites or services that are not owned or controlled
by My Company (change this).
My Company (change this) has no control over, and assumes no responsibility for, the content,
privacy policies, or practices of any third party web sites or services. You further acknowledge and
agree that My Company (change this) shall not be responsible or liable, directly or indirectly, for any
damage or loss caused or alleged to be caused by or in connection with use of or reliance on any
such content, goods or services available on or through any such web sites or services.
        </p>
<h2>Changes</h2>
    <p>
We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a
revision is material we will try to provide at least 30 (change this) days' notice prior to any new terms
taking effect. What constitutes a material change will be determined at our sole discretion.
Contact Us
If you have any questions about these Terms, please contact us.
    </p>

</body>
</html>

accounts/templates/accounts/signup_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>FanVault Registration</title>
</head>
<body>
<h5>Hi {{ name }}</h5><br>
<h5>Your registration is almost complete.</h5><br>
<h4><a href="{{ email_confirmation_url }}">Click here</a> to activate your account.</h4>

</body>
</html>

accounts/templates/accounts/terms_and_conditions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Terms and Conditions</title>
    <style>
        .title{
            text-align:center;
        }
    </style>
</head>
<body>
<h1 class="title">Terms and Conditions ("Terms")</h1>
<p>Last updated: (12-8-2016)</p>
<p>
Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using
the http://www.mywebsite.com (change this) website and the My Mobile App (change this) mobile
application (the "Service") operated by My Company (change this) ("us", "we", or "our").
Your access to and use of the Service is conditioned on your acceptance of and compliance with
these Terms. These Terms apply to all visitors, users and others who access or use the Service.
By accessing or using the Service you agree to be bound by these Terms. If you disagree
with any part of the terms then you may not access the Service. </p>
<h2>Purchases</h2>
<p>
If you wish to purchase any product or service made available through the Service ("Purchase"),
you may be asked to supply certain information relevant to your Purchase including, without
limitation, your …
The Purchases section is for businesses that sell online (physical or digital). For the full
disclosure section, create your own Terms and Conditions.
    </p>
<h2>Subscriptions</h2>
    <p>
Some parts of the Service are billed on a subscription basis ("Subscription(s)"). You will be billed in
advance on a recurring ...
The Subscriptions section is for SaaS businesses. For the full disclosure section, create your
own Terms and Conditions.
        </p>
<h2>Content</h2>
    <p>
Our Service allows you to post, link, store, share and otherwise make available certain information,
text, graphics, videos, or other material ("Content"). You are responsible for the …
The Content section is for businesses that allow users to create, edit, share, make content on
their websites or apps. For the full disclosure section, create your own Terms and Conditions.
Links To Other Web Sites
Our Service may contain links to third­party web sites or services that are not owned or controlled
by My Company (change this).
My Company (change this) has no control over, and assumes no responsibility for, the content,
privacy policies, or practices of any third party web sites or services. You further acknowledge and
agree that My Company (change this) shall not be responsible or liable, directly or indirectly, for any
damage or loss caused or alleged to be caused by or in connection with use of or reliance on any
such content, goods or services available on or through any such web sites or services.
        </p>
<h2>Changes</h2>
    <p>
We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a
revision is material we will try to provide at least 30 (change this) days' notice prior to any new terms
taking effect. What constitutes a material change will be determined at our sole discretion.
Contact Us
If you have any questions about these Terms, please contact us.
    </p>

</body>
</html>